from __future__ import annotations

import os
import re
import shutil
import struct
import subprocess
from dataclasses import dataclass
from pathlib import Path

import pytest

from tests.ie_formats import write_minimal_bg2ee_key_biff, write_minimal_tlk
from tests.test_localization import parse_tra


ROOT = Path(__file__).resolve().parents[1]
FALLBACK_WEIDU = Path(r"C:\src\private\chriz-bg-rebalance\weidu.exe")
RELEASED_V170_TP2 = ROOT / "tests/fixtures/setup-buffbot-v1.7.0-alpha.tp2"
MAP_BACKED_V174_TP2 = (
    ROOT / "tests/fixtures/setup-buffbot-map-backed-v1.7.4-alpha.tp2"
)
KEEP_BYTES = b"unrelated override sentinel\n"
SOURCE_LUA51 = b"synthetic EEex lua51.dll\0"
SOURCE_PROVIDER = b"synthetic EEex LuaProvider.dll\0"
REQUIREMENT_TEXT = "BuffBot requires EEex v0.11.0-alpha or later"
MAIN_LUAJIT_REQUIREMENT_TEXT = (
    "BuffBot requires EEex LuaJIT to be active before installing the main component"
)
LANGUAGE_CASES = (
    (0, "en_US", "english"),
    (1, "zh_CN", "schinese"),
    (2, "it_IT", "italian"),
    (3, "de_DE", "german"),
    (4, "fr_FR", "french"),
    (5, "es_ES", "spanish"),
    (6, "pl_PL", "polish"),
    (7, "ru_RU", "russian"),
    (8, "pt_BR", "brazilian_portuguese"),
)
GAME_TLK_ATTRIBUTES = {
    "en_US": "lang_tlk",
    "zh_CN": "schinese_tlk",
    "it_IT": "italian_tlk",
    "de_DE": "german_tlk",
    "fr_FR": "french_tlk",
    "es_ES": "spanish_tlk",
    "pl_PL": "polish_tlk",
    "ru_RU": "russian_tlk",
    "pt_BR": "brazilian_portuguese_tlk",
}
ENGLISH_CATALOG, _ = parse_tra(ROOT / "buffbot/lang/english/setup.tra")
INNATE_CATALOG_IDS = set(range(200, 208))

MAIN_OUTPUT_FILES = {
    "m_bfbot.lua",
    "bfbotcor.lua",
    "bfbotloc.lua",
    "bfbotcls.lua",
    "bfbotscn.lua",
    "bfbot5e.lua",
    "bfbotexe.lua",
    "bfbotmp.lua",
    "bfbotper.lua",
    "bfbotinn.lua",
    "bfbotui.lua",
    "bfbotthm.lua",
    "bfbottst.lua",
    "buffbot.menu",
    "bfbotib.bam",
    "bfbotbg.mos",
    "mos9900.pvrz",
    "mos9901.pvrz",
    "mos9902.pvrz",
    "mos9903.pvrz",
    "bfbotfr.pvrz",
    "bfbotab.bam",
    "mos9910.pvrz",
    "mos9911.pvrz",
    "mos9912.pvrz",
    "mos9913.pvrz",
    "bfbotfr2.pvrz",
    "mos9920.pvrz",
    "mos9921.pvrz",
    "mos9922.pvrz",
    "mos9923.pvrz",
    "bfbotfr3.pvrz",
    "bfbot_strrefs.txt",
    "bfbot_l10n.tra",
}

CAPABILITY_CASES = (
    ("none", False),
    ("log_only", False),
    ("v010", False),
    ("v010_stale_options", False),
    ("v011", True),
    ("v1", True),
    ("ambiguous", False),
)


def _official_loader_ini(
    general_assignments: tuple[str, ...] = (),
    hardcoded_assignments: tuple[str, ...] = (),
    *,
    newline: str = "\n",
) -> str:
    """Return an InfinityLoader.ini shaped like the files shipped by EEex."""
    return newline.join(
        (
            "[General]",
            "Debug=0",
            *general_assignments,
            "Pause=0",
            "",
            "[Auto-Generated]",
            "SyntheticAutoGeneratedValue=preserve-me",
            "",
            "[Hardcoded_InternalLuaState]",
            "SyntheticPattern=preserve-me-too",
            *hardcoded_assignments,
            "",
        )
    )


def _loader_with_custom_section_before_auto(version: str, newline: str) -> str:
    return newline.join(
        (
            "[General]",
            "Debug=0",
            "Pause=0",
            "",
            "[Custom]",
            "SyntheticCustomValue=preserve-custom",
            "LuaPatchMode=REPLACE_INTERNAL_WITH_EXTERNAL",
            "LuaLibrary=lua51.dll",
            f"LuaVersionExternal={version}",
            "",
            "[Auto-Generated]",
            "SyntheticAutoGeneratedValue=preserve-me",
            "",
            "[Hardcoded_InternalLuaState]",
            "SyntheticPattern=preserve-me-too",
            "",
        )
    )


def _assert_only_general_luajit_assignments(ini: str, version: str) -> None:
    expected = {
        "LuaPatchMode": "REPLACE_INTERNAL_WITH_EXTERNAL",
        "LuaLibrary": "lua51.dll",
        "LuaVersionExternal": version,
    }
    found: dict[str, list[tuple[str | None, str]]] = {
        key: [] for key in expected
    }
    section: str | None = None
    for line in ini.splitlines():
        header = re.fullmatch(r"\[([^]]+)]", line)
        if header:
            section = header.group(1)
            continue
        assignment = re.fullmatch(
            r"(LuaPatchMode|LuaLibrary|LuaVersionExternal)=(.*)", line
        )
        if assignment:
            found[assignment.group(1)].append((section, assignment.group(2)))

    for key, value in expected.items():
        assert found[key] == [("General", value)]
    assert ini.index("LuaPatchMode=") < ini.index("[Auto-Generated]")
    assert "SyntheticAutoGeneratedValue=preserve-me" in ini
    assert "SyntheticPattern=preserve-me-too" in ini


def _weidu() -> Path:
    configured = os.environ.get("WEIDU_EXE")
    result = Path(configured) if configured else FALLBACK_WEIDU
    if not result.is_file():
        pytest.fail(f"WeiDU executable not found: {result}")
    return result


def _assert_weidu_249(process: subprocess.CompletedProcess[str]) -> None:
    transcript = f"{process.stdout}\n{process.stderr}".strip()
    assert process.returncode == 0, transcript
    versions = re.findall(r"WeiDU version (\d+)", transcript)
    assert len(versions) == 1, transcript
    assert int(versions[0]) == 24900, transcript


@pytest.fixture(scope="module", autouse=True)
def _require_weidu_249_for_installer_lifecycle() -> None:
    _assert_weidu_249(
        subprocess.run(
            [str(_weidu()), "--version"],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=30,
            check=False,
        )
    )


def _file_bytes(path: Path) -> bytes | None:
    return path.read_bytes() if path.is_file() else None


def _file_tree(path: Path) -> dict[str, bytes]:
    if not path.is_dir():
        return {}
    result: dict[str, bytes] = {}
    for candidate in sorted(item for item in path.rglob("*") if item.is_file()):
        relative = candidate.relative_to(path).as_posix().casefold()
        if relative in result:
            raise AssertionError(f"case-colliding synthetic file: {relative}")
        result[relative] = candidate.read_bytes()
    return result


def _read_tlk_strings(path: Path) -> list[str]:
    data = path.read_bytes()
    if data[:8] != b"TLK V1  ":
        raise AssertionError(f"not a TLK V1 file: {path}")
    count = struct.unpack_from("<I", data, 0x0A)[0]
    strings_offset = struct.unpack_from("<I", data, 0x0E)[0]
    strings: list[str] = []
    for index in range(count):
        entry = 0x12 + index * 26
        offset, length = struct.unpack_from("<II", data, entry + 18)
        strings.append(
            data[strings_offset + offset : strings_offset + offset + length].decode(
                "utf-8", errors="replace"
            )
        )
    return strings


def _write_tlk_strings(path: Path, strings: tuple[str, ...]) -> None:
    encoded = [value.encode("utf-8") for value in strings]
    strings_offset = 0x12 + len(encoded) * 26
    entries: list[bytes] = []
    payload = bytearray()
    for value in encoded:
        entries.append(
            struct.pack(
                "<H8siiII",
                1 if value else 0,
                b"\0" * 8,
                0,
                0,
                len(payload),
                len(value),
            )
        )
        payload.extend(value)
    path.write_bytes(
        struct.pack("<8sHII", b"TLK V1  ", 0, len(encoded), strings_offset)
        + b"".join(entries)
        + payload
    )


def _read_innate_strrefs(game: "BuffBotGame") -> list[int]:
    rows = (
        (game.override / "bfbot_strrefs.txt")
        .read_text(encoding="ascii")
        .splitlines()
    )
    assert len(rows) == 8
    assert all(re.fullmatch(r"\d+", row) for row in rows)
    return [int(row) for row in rows]


def _game_tlk(game: "BuffBotGame", game_language: str) -> Path:
    try:
        attribute = GAME_TLK_ATTRIBUTES[game_language]
    except KeyError as error:
        message = f"unsupported synthetic game language: {game_language}"
        raise AssertionError(message) from error
    return getattr(game, attribute)


def _assert_selected_runtime_catalog(
    game: "BuffBotGame",
    *,
    game_language: str,
    catalog_directory: str,
    expected_tlk_strings: set[str] | None = None,
) -> list[int]:
    catalog_path = ROOT / "buffbot" / "lang" / catalog_directory / "setup.tra"
    catalog, _ = parse_tra(catalog_path)
    assert (game.override / "bfbot_l10n.tra").read_bytes() == catalog_path.read_bytes()
    assert not (game.override / "bfbot_l10n.txt").exists()

    active_tlk = _game_tlk(game, game_language)
    active_strings = _read_tlk_strings(active_tlk)

    if expected_tlk_strings is None:
        expected_tlk_strings = {
            catalog[catalog_id] for catalog_id in INNATE_CATALOG_IDS
        }
    assert active_strings[0] == ""
    assert len(active_strings) == 1 + len(expected_tlk_strings)
    assert set(active_strings[1:]) == expected_tlk_strings

    innate_strrefs = _read_innate_strrefs(game)
    assert all(0 <= strref < len(active_strings) for strref in innate_strrefs)
    assert [active_strings[strref] for strref in innate_strrefs] == [
        catalog[catalog_id] for catalog_id in range(200, 208)
    ]
    return innate_strrefs


def _active_buffbot_log_entries(game: "BuffBotGame") -> list[tuple[int, int]]:
    active: list[tuple[int, int]] = []
    for line in (game.root / "WeiDU.log").read_text(encoding="utf-8").splitlines():
        if not line.startswith("~"):
            continue
        normalized = line.replace("\\", "/").casefold()
        if "buffbot/setup-buffbot.tp2~" not in normalized:
            continue
        language_and_component = re.search(r"#(\d+)\s+#(\d+)", normalized)
        assert language_and_component is not None, line
        active.append(
            (
                int(language_and_component.group(1)),
                int(language_and_component.group(2)),
            )
        )
    return active


def _assert_english_innate_catalog_in_tlk(path: Path) -> None:
    strings = _read_tlk_strings(path)
    expected_values = {
        ENGLISH_CATALOG[catalog_id] for catalog_id in INNATE_CATALOG_IDS
    }
    assert strings[0] == ""
    assert expected_values <= set(strings[1:])
    assert set(strings[1:]) <= set(ENGLISH_CATALOG.values())


@dataclass(frozen=True)
class ProductState:
    key: bytes
    bif: bytes
    root_tlk: bytes
    lang_tlk: bytes
    schinese_tlk: bytes
    italian_tlk: bytes
    german_tlk: bytes
    french_tlk: bytes
    spanish_tlk: bytes
    polish_tlk: bytes
    russian_tlk: bytes
    brazilian_portuguese_tlk: bytes
    override: dict[str, bytes]
    eeex: dict[str, bytes]
    eeex_scripts: dict[str, bytes]
    loader_ini: bytes | None
    root_lua51: bytes | None
    root_provider: bytes | None


def _state_tlk(state: ProductState, game_language: str) -> bytes:
    try:
        attribute = GAME_TLK_ATTRIBUTES[game_language]
    except KeyError as error:
        message = f"unsupported synthetic game language: {game_language}"
        raise AssertionError(message) from error
    return getattr(state, attribute)


class BuffBotGame:
    def __init__(self, root: Path, layout: str, *, with_log: bool = True) -> None:
        self.root = root
        self.root.mkdir()
        self.override = root / "override"
        self.override.mkdir()
        self.bif = write_minimal_bg2ee_key_biff(root)
        self.root_tlk = root / "dialog.tlk"
        self.lang_tlk = root / "lang/en_US/dialog.tlk"
        self.schinese_tlk = root / "lang/zh_CN/dialog.tlk"
        self.italian_tlk = root / "lang/it_IT/dialog.tlk"
        self.german_tlk = root / "lang/de_DE/dialog.tlk"
        self.french_tlk = root / "lang/fr_FR/dialog.tlk"
        self.spanish_tlk = root / "lang/es_ES/dialog.tlk"
        self.polish_tlk = root / "lang/pl_PL/dialog.tlk"
        self.russian_tlk = root / "lang/ru_RU/dialog.tlk"
        self.brazilian_portuguese_tlk = root / "lang/pt_BR/dialog.tlk"
        write_minimal_tlk(self.root_tlk)
        write_minimal_tlk(self.lang_tlk)
        write_minimal_tlk(self.schinese_tlk)
        write_minimal_tlk(self.italian_tlk)
        write_minimal_tlk(self.german_tlk)
        write_minimal_tlk(self.french_tlk)
        write_minimal_tlk(self.spanish_tlk)
        write_minimal_tlk(self.polish_tlk)
        write_minimal_tlk(self.russian_tlk)
        write_minimal_tlk(self.brazilian_portuguese_tlk)
        shutil.copytree(ROOT / "buffbot", root / "buffbot")
        (self.override / "KEEP.ME").write_bytes(KEEP_BYTES)
        self._build_layout(layout, with_log=with_log)

    @property
    def expected_version(self) -> str:
        old = (self.override / "EEex_Sprite.lua").is_file()
        new = (self.root / "EEex_scripts/EEex_Sprite.lua").is_file()
        if old == new:
            raise AssertionError("fixture does not have exactly one EEex family")
        return "5.1" if old else "5.1-LuaJIT"

    @property
    def source_lua51(self) -> Path:
        return self.root / "EEex/loader/LuaJIT/lua51.dll"

    @property
    def source_provider(self) -> Path:
        return self.root / "EEex/loader/LuaJIT/LuaProvider.dll"

    def _write(self, relative: str, data: str | bytes) -> None:
        path = self.root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        if isinstance(data, str):
            path.write_text(data, encoding="ascii", newline="\n")
        else:
            path.write_bytes(data)

    def _write_log(self, component: int) -> None:
        self._write(
            "WeiDU.log",
            f"~EEEX/EEEX.TP2~ #0 #{component} // synthetic EEex fixture\n",
        )

    def _write_sources(self) -> None:
        self._write("EEex/loader/LuaJIT/lua51.dll", SOURCE_LUA51)
        self._write("EEex/loader/LuaJIT/LuaProvider.dll", SOURCE_PROVIDER)

    def _write_active_loader(self, version: str, newline: str = "\r\n") -> None:
        self._write(
            "InfinityLoader.ini",
            _official_loader_ini(
                (
                    "LuaPatchMode=REPLACE_INTERNAL_WITH_EXTERNAL",
                    "LuaLibrary=lua51.dll",
                    f"LuaVersionExternal={version}",
                ),
                newline=newline,
            ).encode("ascii"),
        )
        self._write("lua51.dll", SOURCE_LUA51)
        self._write("LuaProvider.dll", SOURCE_PROVIDER)

    def set_exact_active_loader(self, newline: str) -> None:
        self._write_active_loader(self.expected_version, newline)

    def _build_layout(self, layout: str, *, with_log: bool) -> None:
        if layout == "none":
            return
        if layout == "log_only":
            if with_log:
                self._write_log(0)
            return

        self._write("override/M___EEex.lua", "-- synthetic EEex bootstrap\n")
        if layout in {"v010", "v010_stale_options"}:
            self._write("override/EEex_Sprite.lua", "-- no required API here\n")
            if layout == "v010_stale_options":
                self._write("override/EEex_Options.lua", "-- stale options\n")
            if with_log:
                self._write_log(0)
            return

        if layout in {"v011", "ambiguous"}:
            self._write(
                "override/EEex_Sprite.lua",
                "function EEex_Sprite_GetCharacterIndex(sprite) return 0 end\n",
            )
            self._write("override/EEex_Options.lua", "-- v0.11 options\n")
        if layout in {"v1", "ambiguous"}:
            self._write(
                "EEex_scripts/EEex_Sprite.lua",
                "function EEex_Sprite_GetCharacterIndex(sprite) return 0 end\n",
            )
            self._write("EEex_scripts/EEex_Options.lua", "-- v1 options\n")

        if layout not in {"v011", "v1", "ambiguous"}:
            raise ValueError(f"unknown EEex layout: {layout}")

        self._write_sources()
        if layout == "v011":
            self._write("EEex/EEex.tp2", "// old fixture: LuaVersionExternal=5.1\n")
            self._write_active_loader("5.1")
            if with_log:
                self._write_log(0)
        else:
            self._write(
                "EEex/EEex.tp2", "// v1 fixture: LuaVersionExternal=5.1-LuaJIT\n"
            )
            self._write_active_loader("5.1-LuaJIT")
            if with_log:
                self._write_log(1)

    def set_tp2(self, contents: str | None) -> None:
        path = self.root / "EEex/EEex.tp2"
        if contents is None:
            path.unlink(missing_ok=True)
        else:
            self._write("EEex/EEex.tp2", contents)

    def configure_loader(
        self,
        ini: str | None,
        *,
        root_lua51: bytes | None = None,
        root_provider: bytes | None = None,
    ) -> None:
        ini_path = self.root / "InfinityLoader.ini"
        if ini is None:
            ini_path.unlink(missing_ok=True)
        else:
            self._write("InfinityLoader.ini", ini)
        for name, payload in (
            ("lua51.dll", root_lua51),
            ("LuaProvider.dll", root_provider),
        ):
            path = self.root / name
            if payload is None:
                path.unlink(missing_ok=True)
            else:
                path.write_bytes(payload)

    def snapshot(self) -> ProductState:
        return ProductState(
            key=(self.root / "chitin.key").read_bytes(),
            bif=self.bif.read_bytes(),
            root_tlk=self.root_tlk.read_bytes(),
            lang_tlk=self.lang_tlk.read_bytes(),
            schinese_tlk=self.schinese_tlk.read_bytes(),
            italian_tlk=self.italian_tlk.read_bytes(),
            german_tlk=self.german_tlk.read_bytes(),
            french_tlk=self.french_tlk.read_bytes(),
            spanish_tlk=self.spanish_tlk.read_bytes(),
            polish_tlk=self.polish_tlk.read_bytes(),
            russian_tlk=self.russian_tlk.read_bytes(),
            brazilian_portuguese_tlk=self.brazilian_portuguese_tlk.read_bytes(),
            override=_file_tree(self.override),
            eeex=_file_tree(self.root / "EEex"),
            eeex_scripts=_file_tree(self.root / "EEex_scripts"),
            loader_ini=_file_bytes(self.root / "InfinityLoader.ini"),
            root_lua51=_file_bytes(self.root / "lua51.dll"),
            root_provider=_file_bytes(self.root / "LuaProvider.dll"),
        )

    def run_args(
        self,
        *arguments: str | int,
        mod_language: int = 0,
        game_language: str = "en_US",
    ) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [
                str(_weidu()),
                r".\buffbot\setup-buffbot.tp2",
                "--game",
                str(self.root),
                *(str(argument) for argument in arguments),
                "--language",
                str(mod_language),
                "--use-lang",
                game_language,
                "--no-exit-pause",
                "--quick-log",
                "--noautoupdate",
            ],
            cwd=self.root,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=120,
            check=False,
        )

    def run(
        self,
        operation: str,
        *components: int,
        mod_language: int = 0,
        game_language: str = "en_US",
    ) -> subprocess.CompletedProcess[str]:
        return self.run_args(
            operation,
            *components,
            mod_language=mod_language,
            game_language=game_language,
        )

    def install(
        self,
        component: int,
        *,
        mod_language: int = 0,
        game_language: str = "en_US",
    ) -> subprocess.CompletedProcess[str]:
        return self.run(
            "--force-install-list",
            component,
            mod_language=mod_language,
            game_language=game_language,
        )

    def install_many(
        self,
        *components: int,
        mod_language: int = 0,
        game_language: str = "en_US",
    ) -> subprocess.CompletedProcess[str]:
        return self.run(
            "--force-install-list",
            *components,
            mod_language=mod_language,
            game_language=game_language,
        )

    def uninstall(self, component: int) -> subprocess.CompletedProcess[str]:
        return self.run("--force-uninstall-list", component)

    def uninstall_then_install(
        self, uninstall_component: int, install_component: int
    ) -> subprocess.CompletedProcess[str]:
        return self.run_args(
            "--force-uninstall-list",
            uninstall_component,
            "--force-install-list",
            install_component,
        )

    def replace_buffbot_tp2(self, source: Path) -> None:
        shutil.copy2(source, self.root / "buffbot/setup-buffbot.tp2")

    @staticmethod
    def transcript(process: subprocess.CompletedProcess[str]) -> str:
        return f"{process.stdout}\n{process.stderr}".strip()

    def assert_no_main_payload(self) -> None:
        override = _file_tree(self.override)
        assert MAIN_OUTPUT_FILES.isdisjoint(override)

    def assert_main_installed(self, before: ProductState) -> None:
        after = self.snapshot()
        assert after.key == before.key
        assert after.bif == before.bif
        assert after.root_tlk == before.root_tlk
        assert after.eeex == before.eeex
        assert after.eeex_scripts == before.eeex_scripts
        assert after.loader_ini == before.loader_ini
        assert after.root_lua51 == before.root_lua51
        assert after.root_provider == before.root_provider
        assert after.lang_tlk != before.lang_tlk
        for inactive_language in GAME_TLK_ATTRIBUTES.keys() - {"en_US"}:
            assert _state_tlk(after, inactive_language) == _state_tlk(
                before, inactive_language
            )
        _assert_english_innate_catalog_in_tlk(self.lang_tlk)
        assert after.override.keys() == before.override.keys() | MAIN_OUTPUT_FILES
        for name, payload in before.override.items():
            assert after.override[name] == payload
        assert (self.override / "bfbot_presets").is_dir()
        assert (self.override / "KEEP.ME").read_bytes() == KEEP_BYTES

    def assert_luajit_state(self, version: str) -> None:
        ini = (self.root / "InfinityLoader.ini").read_text(encoding="ascii")
        _assert_only_general_luajit_assignments(ini, version)
        assert (self.root / "lua51.dll").read_bytes() == self.source_lua51.read_bytes()
        assert (
            self.root / "LuaProvider.dll"
        ).read_bytes() == self.source_provider.read_bytes()


@pytest.fixture
def game_factory(tmp_path: Path):
    count = 0

    def make(layout: str, *, with_log: bool = True) -> BuffBotGame:
        nonlocal count
        count += 1
        return BuffBotGame(tmp_path / f"game-{count}", layout, with_log=with_log)

    return make


def _assert_installed(game: BuffBotGame, process: subprocess.CompletedProcess[str]) -> str:
    transcript = game.transcript(process)
    assert process.returncode == 0, transcript
    assert "SUCCESSFULLY INSTALLED" in transcript, transcript
    return transcript


def _assert_rejected(
    game: BuffBotGame,
    process: subprocess.CompletedProcess[str],
    before: ProductState,
) -> None:
    transcript = game.transcript(process)
    assert "SUCCESSFULLY INSTALLED" not in transcript, transcript
    assert "SKIPPING" in transcript, transcript
    assert REQUIREMENT_TEXT in transcript, transcript
    assert game.snapshot() == before
    game.assert_no_main_payload()
    assert (game.override / "KEEP.ME").read_bytes() == KEEP_BYTES


def test_weidu_249_gate_rejects_version_prefix_collision() -> None:
    prefix_collision = subprocess.CompletedProcess(
        args=["weidu.exe", "--version"],
        returncode=0,
        stdout="[weidu.exe] WeiDU version 249000\n",
        stderr="",
    )

    with pytest.raises(AssertionError):
        _assert_weidu_249(prefix_collision)


@pytest.mark.parametrize("component", (0, 1))
@pytest.mark.parametrize(("layout", "accepted"), CAPABILITY_CASES)
def test_components_require_eeex_v011_capabilities(
    game_factory, component: int, layout: str, accepted: bool
) -> None:
    game = game_factory(layout)
    before = game.snapshot()
    process = game.install(component)
    if not accepted:
        _assert_rejected(game, process, before)
    elif component == 0:
        _assert_installed(game, process)
        game.assert_main_installed(before)
    else:
        _assert_installed(game, process)
        game.assert_luajit_state(game.expected_version)
        assert game.snapshot() == before


@pytest.mark.parametrize("component", (0, 1))
@pytest.mark.parametrize("layout", ("v011", "v1"))
def test_capable_layouts_do_not_require_weidu_log(
    game_factory, component: int, layout: str
) -> None:
    game = game_factory(layout, with_log=False)
    before = game.snapshot()
    process = game.install(component)
    _assert_installed(game, process)
    if component == 0:
        game.assert_main_installed(before)
    else:
        game.assert_luajit_state(game.expected_version)
        assert game.snapshot() == before


@pytest.mark.parametrize("component", (0, 1))
@pytest.mark.parametrize("layout", ("v011", "v1"))
def test_components_reject_capable_script_layout_without_eeex_bootstrap(
    game_factory, component: int, layout: str
) -> None:
    game = game_factory(layout)
    (game.override / "M___EEex.lua").unlink()
    before = game.snapshot()

    process = game.install(component)

    _assert_rejected(game, process, before)


def test_installer_source_does_not_gate_on_eeex_component_numbers() -> None:
    source = (ROOT / "buffbot/setup-buffbot.tp2").read_text(encoding="utf-8")
    assert not re.search(
        r"MOD_IS_INSTALLED(?:(?!MOD_IS_INSTALLED).){0,200}EEex[/\\]EEex[.]tp2",
        source,
        re.IGNORECASE | re.DOTALL,
    )


def test_luajit_helper_is_declared_before_main_with_stable_component_ids() -> None:
    source = (ROOT / "buffbot/setup-buffbot.tp2").read_text(encoding="utf-8")
    helper_begin = source.index("LABEL ~BuffBot-LuaJIT~")
    main_begin = source.index("LABEL ~BuffBot-Main~")

    assert helper_begin < main_begin
    assert "DESIGNATED 1" in source[source.rfind("BEGIN", 0, helper_begin):helper_begin]
    assert "DESIGNATED 0" in source[source.rfind("BEGIN", 0, main_begin):main_begin]


@pytest.mark.parametrize("layout", ("v011", "v1"))
@pytest.mark.parametrize(
    ("mod_language", "game_language", "catalog_directory"),
    LANGUAGE_CASES,
)
def test_installer_localization_selects_one_tlk_and_installs_exact_runtime_catalog(
    game_factory,
    layout: str,
    mod_language: int,
    game_language: str,
    catalog_directory: str,
) -> None:
    game = game_factory(layout)
    game.configure_loader(
        _official_loader_ini(
            (
                "LuaPatchMode=INTERNAL",
                "LuaLibrary=lua52.dll",
                "LuaVersionExternal=5.2",
            )
        )
    )
    before = game.snapshot()
    catalog, _ = parse_tra(
        ROOT / "buffbot" / "lang" / catalog_directory / "setup.tra"
    )
    process = game.install_many(
        1,
        0,
        mod_language=mod_language,
        game_language=game_language,
    )
    transcript = _assert_installed(game, process)
    assert transcript.index(catalog[100]) < transcript.index(catalog[111])
    assert catalog[107] in transcript
    assert catalog[108].replace("%lua_version%", game.expected_version) in transcript
    assert "%lua_version%" not in transcript
    assert catalog[109] in transcript

    for inactive_language in GAME_TLK_ATTRIBUTES.keys() - {game_language}:
        assert _game_tlk(game, inactive_language).read_bytes() == _state_tlk(
            before, inactive_language
        )
    assert game.root_tlk.read_bytes() == before.root_tlk
    _assert_selected_runtime_catalog(
        game,
        game_language=game_language,
        catalog_directory=catalog_directory,
    )

    text_payloads = sorted(
        relative
        for relative in MAIN_OUTPUT_FILES
        if Path(relative).suffix in {".lua", ".menu", ".txt"}
    )
    for relative in text_payloads:
        installed = (game.override / relative).read_text(encoding="utf-8")
        assert "BFBOTUITRA_" not in installed
    installed_refs = (game.override / "bfbot_strrefs.txt").read_text(
        encoding="ascii"
    )
    assert re.search(r"@\d+", installed_refs) is None
    assert re.search(r"%[A-Za-z_][A-Za-z0-9_]*%", installed_refs) is None
    assert (game.override / "bfbot_l10n.tra").read_bytes() == (
        ROOT / "buffbot" / "lang" / catalog_directory / "setup.tra"
    ).read_bytes()


def test_main_component_restores_preexisting_selected_catalog_on_uninstall(
    game_factory,
) -> None:
    game = game_factory("v011")
    sentinel = b"pre-existing runtime catalog owned by another component\r\n"
    selected_catalog = game.override / "bfbot_l10n.tra"
    selected_catalog.write_bytes(sentinel)
    before = game.snapshot()

    install = game.install(0)
    _assert_installed(game, install)
    _assert_selected_runtime_catalog(
        game,
        game_language="en_US",
        catalog_directory="english",
    )
    installed_tlk = game.lang_tlk.read_bytes()

    uninstall = game.uninstall(0)
    transcript = game.transcript(uninstall)
    assert uninstall.returncode == 0, transcript
    assert "NOT UNINSTALLED" not in transcript, transcript
    assert selected_catalog.read_bytes() == sentinel
    assert not (game.override / "bfbot_l10n.txt").exists()
    assert game.snapshot().override == before.override
    assert game.lang_tlk.read_bytes() == installed_tlk
    assert game.root_tlk.read_bytes() == before.root_tlk
    assert game.schinese_tlk.read_bytes() == before.schinese_tlk


def test_map_backed_candidate_migrates_in_one_forced_uninstall_install(
    game_factory,
) -> None:
    fixture_source = MAP_BACKED_V174_TP2.read_text(encoding="utf-8")
    assert "bfbot_l10n.generated" in fixture_source
    assert "override/bfbot_l10n.txt" in fixture_source

    game = game_factory("v011")
    baseline = game.snapshot()
    game.replace_buffbot_tp2(MAP_BACKED_V174_TP2)
    _assert_installed(game, game.install(0))
    assert (game.override / "bfbot_l10n.txt").is_file()
    assert not (game.override / "bfbot_l10n.tra").exists()
    legacy_tlk = game.lang_tlk.read_bytes()
    legacy_strings = set(_read_tlk_strings(game.lang_tlk)[1:])

    game.replace_buffbot_tp2(ROOT / "buffbot/setup-buffbot.tp2")
    migration = game.run_args(
        "--force-uninstall-list",
        0,
        "--force-install-list",
        0,
        mod_language=0,
        game_language="en_US",
    )
    transcript = _assert_installed(game, migration)
    assert transcript.count("SUCCESSFULLY REMOVED") == 1
    assert transcript.count("SUCCESSFULLY INSTALLED") == 1
    assert transcript.index("SUCCESSFULLY REMOVED") < transcript.rindex(
        "SUCCESSFULLY INSTALLED"
    )
    assert not (game.override / "bfbot_l10n.txt").exists()
    _assert_selected_runtime_catalog(
        game,
        game_language="en_US",
        catalog_directory="english",
        expected_tlk_strings=legacy_strings,
    )
    assert game.lang_tlk.read_bytes() == legacy_tlk
    assert _active_buffbot_log_entries(game) == [(0, 0)]

    uninstall = game.uninstall(0)
    uninstall_transcript = game.transcript(uninstall)
    assert uninstall.returncode == 0, uninstall_transcript
    assert "NOT UNINSTALLED" not in uninstall_transcript, uninstall_transcript
    assert not (game.override / "bfbot_l10n.tra").exists()
    assert not (game.override / "bfbot_l10n.txt").exists()
    after = game.snapshot()
    assert after.override == baseline.override
    assert after.key == baseline.key
    assert after.bif == baseline.bif
    assert after.root_tlk == baseline.root_tlk
    assert after.schinese_tlk == baseline.schinese_tlk
    assert after.loader_ini == baseline.loader_ini
    assert after.root_lua51 == baseline.root_lua51
    assert after.root_provider == baseline.root_provider
    assert after.lang_tlk == legacy_tlk
    assert _active_buffbot_log_entries(game) == []


@pytest.mark.parametrize("layout", ("v011", "v1"))
@pytest.mark.parametrize(
    ("target_mod_language", "target_game_language", "target_catalog_directory"),
    LANGUAGE_CASES[1:],
)
def test_language_switch_reinstalls_main_and_reuses_selected_tlk_strrefs(
    game_factory,
    layout: str,
    target_mod_language: int,
    target_game_language: str,
    target_catalog_directory: str,
) -> None:
    game = game_factory(layout)
    game.configure_loader(
        _official_loader_ini(
            (
                "LuaPatchMode=INTERNAL",
                "LuaLibrary=lua52.dll",
                "LuaVersionExternal=5.2",
            )
        )
    )
    baseline = game.snapshot()
    english_catalog, _ = parse_tra(ROOT / "buffbot/lang/english/setup.tra")
    target_catalog, _ = parse_tra(
        ROOT / "buffbot" / "lang" / target_catalog_directory / "setup.tra"
    )

    fresh_english = game.install_many(
        1,
        0,
        mod_language=0,
        game_language="en_US",
    )
    english_transcript = _assert_installed(game, fresh_english)
    assert english_transcript.count("SUCCESSFULLY INSTALLED") == 2
    assert "NOT INSTALLED DUE TO ERRORS" not in english_transcript
    assert "ERROR Installing" not in english_transcript
    assert english_transcript.index(english_catalog[100]) < english_transcript.index(
        english_catalog[111]
    )
    game.assert_luajit_state(game.expected_version)

    after_english = game.snapshot()
    assert after_english.key == baseline.key
    assert after_english.bif == baseline.bif
    assert after_english.root_tlk == baseline.root_tlk
    assert after_english.lang_tlk != baseline.lang_tlk
    for inactive_language in GAME_TLK_ATTRIBUTES.keys() - {"en_US"}:
        assert _state_tlk(after_english, inactive_language) == _state_tlk(
            baseline, inactive_language
        )
    _assert_selected_runtime_catalog(
        game,
        game_language="en_US",
        catalog_directory="english",
    )
    english_catalog_bytes = (game.override / "bfbot_l10n.tra").read_bytes()
    english_innate_refs_bytes = (game.override / "bfbot_strrefs.txt").read_bytes()
    english_payload = {
        name: payload
        for name, payload in after_english.override.items()
        if name not in {"bfbot_l10n.tra", "bfbot_strrefs.txt"}
    }
    helper_state = (
        after_english.loader_ini,
        after_english.root_lua51,
        after_english.root_provider,
    )
    helper_backup = _file_tree(game.root / "weidu_external/backup/buffbot/1")
    assert helper_backup
    assert _active_buffbot_log_entries(game) == [(0, 1), (0, 0)]

    switch_to_target = game.run_args(
        "--force-uninstall-list",
        0,
        "--force-install-list",
        0,
        mod_language=target_mod_language,
        game_language=target_game_language,
    )
    target_transcript = _assert_installed(game, switch_to_target)
    assert target_transcript.count("SUCCESSFULLY REMOVED") == 1
    assert target_transcript.count("SUCCESSFULLY INSTALLED") == 1
    assert "NOT INSTALLED DUE TO ERRORS" not in target_transcript
    assert "ERROR Installing" not in target_transcript
    assert target_transcript.index("SUCCESSFULLY REMOVED") < target_transcript.rindex(
        "SUCCESSFULLY INSTALLED"
    )
    assert target_catalog[111] in target_transcript

    after_target = game.snapshot()
    assert after_target.key == baseline.key
    assert after_target.bif == baseline.bif
    assert after_target.root_tlk == baseline.root_tlk
    assert after_target.lang_tlk == after_english.lang_tlk
    assert _state_tlk(after_target, target_game_language) != _state_tlk(
        baseline, target_game_language
    )
    for inactive_language in GAME_TLK_ATTRIBUTES.keys() - {
        "en_US",
        target_game_language,
    }:
        assert _state_tlk(after_target, inactive_language) == _state_tlk(
            baseline, inactive_language
        )
    _assert_selected_runtime_catalog(
        game,
        game_language=target_game_language,
        catalog_directory=target_catalog_directory,
    )
    assert {
        name: payload
        for name, payload in after_target.override.items()
        if name not in {"bfbot_l10n.tra", "bfbot_strrefs.txt"}
    } == english_payload
    assert (
        after_target.loader_ini,
        after_target.root_lua51,
        after_target.root_provider,
    ) == helper_state
    assert _file_tree(game.root / "weidu_external/backup/buffbot/1") == helper_backup
    assert _active_buffbot_log_entries(game) == [(0, 1), (target_mod_language, 0)]

    switch_back_to_english = game.run_args(
        "--force-uninstall-list",
        0,
        "--force-install-list",
        0,
        mod_language=0,
        game_language="en_US",
    )
    return_transcript = _assert_installed(game, switch_back_to_english)
    assert return_transcript.count("SUCCESSFULLY REMOVED") == 1
    assert return_transcript.count("SUCCESSFULLY INSTALLED") == 1
    assert "NOT INSTALLED DUE TO ERRORS" not in return_transcript
    assert "ERROR Installing" not in return_transcript
    assert return_transcript.index("SUCCESSFULLY REMOVED") < return_transcript.rindex(
        "SUCCESSFULLY INSTALLED"
    )
    assert english_catalog[111] in return_transcript

    after_return = game.snapshot()
    assert after_return.key == baseline.key
    assert after_return.bif == baseline.bif
    assert after_return.root_tlk == baseline.root_tlk
    assert after_return.lang_tlk == after_english.lang_tlk
    assert _state_tlk(after_return, target_game_language) == _state_tlk(
        after_target, target_game_language
    )
    for inactive_language in GAME_TLK_ATTRIBUTES.keys() - {
        "en_US",
        target_game_language,
    }:
        assert _state_tlk(after_return, inactive_language) == _state_tlk(
            baseline, inactive_language
        )
    _assert_selected_runtime_catalog(
        game,
        game_language="en_US",
        catalog_directory="english",
    )
    assert (
        game.override / "bfbot_l10n.tra"
    ).read_bytes() == english_catalog_bytes
    assert (
        game.override / "bfbot_strrefs.txt"
    ).read_bytes() == english_innate_refs_bytes
    assert after_return.override == after_english.override
    assert (
        after_return.loader_ini,
        after_return.root_lua51,
        after_return.root_provider,
    ) == helper_state
    assert _file_tree(game.root / "weidu_external/backup/buffbot/1") == helper_backup
    assert _active_buffbot_log_entries(game) == [(0, 1), (0, 0)]


@pytest.mark.parametrize("layout", ("v011", "v1"))
@pytest.mark.parametrize("fixed_game_language", ("en_US", "zh_CN"))
def test_language_switch_reuses_one_fixed_game_tlk_without_duplicate_growth(
    game_factory, layout: str, fixed_game_language: str
) -> None:
    game = game_factory(layout)
    game.configure_loader(
        _official_loader_ini(
            (
                "LuaPatchMode=INTERNAL",
                "LuaLibrary=lua52.dll",
                "LuaVersionExternal=5.2",
            )
        )
    )
    selected_tlk = (
        game.lang_tlk
        if fixed_game_language == "en_US"
        else game.schinese_tlk
    )
    inactive_tlk = (
        game.schinese_tlk
        if fixed_game_language == "en_US"
        else game.lang_tlk
    )
    sentinel = "pre-existing fixed TLK sentinel"
    _write_tlk_strings(selected_tlk, ("", sentinel))
    baseline = game.snapshot()
    inactive_baseline = inactive_tlk.read_bytes()

    english_catalog, _ = parse_tra(ROOT / "buffbot/lang/english/setup.tra")
    chinese_catalog, _ = parse_tra(ROOT / "buffbot/lang/schinese/setup.tra")
    english_innate_strings = {
        english_catalog[catalog_id] for catalog_id in INNATE_CATALOG_IDS
    }
    chinese_innate_strings = {
        chinese_catalog[catalog_id] for catalog_id in INNATE_CATALOG_IDS
    }
    english_tlk_strings = {sentinel} | english_innate_strings
    union_tlk_strings = english_tlk_strings | chinese_innate_strings

    fresh_english = game.install_many(
        1,
        0,
        mod_language=0,
        game_language=fixed_game_language,
    )
    english_transcript = _assert_installed(game, fresh_english)
    assert english_transcript.count("SUCCESSFULLY INSTALLED") == 2
    assert "NOT INSTALLED DUE TO ERRORS" not in english_transcript
    assert "ERROR Installing" not in english_transcript

    after_english = game.snapshot()
    assert game.root_tlk.read_bytes() == baseline.root_tlk
    assert inactive_tlk.read_bytes() == inactive_baseline
    _assert_selected_runtime_catalog(
        game,
        game_language=fixed_game_language,
        catalog_directory="english",
        expected_tlk_strings=english_tlk_strings,
    )
    english_strings = _read_tlk_strings(selected_tlk)
    assert english_strings[1] == sentinel
    english_catalog_bytes = (game.override / "bfbot_l10n.tra").read_bytes()
    english_innate_refs_bytes = (game.override / "bfbot_strrefs.txt").read_bytes()
    english_payload = {
        name: payload
        for name, payload in after_english.override.items()
        if name not in {"bfbot_l10n.tra", "bfbot_strrefs.txt"}
    }
    helper_state = (
        after_english.loader_ini,
        after_english.root_lua51,
        after_english.root_provider,
    )
    helper_backup = _file_tree(game.root / "weidu_external/backup/buffbot/1")
    assert helper_backup
    assert _active_buffbot_log_entries(game) == [(0, 1), (0, 0)]

    switch_to_chinese = game.run_args(
        "--force-uninstall-list",
        0,
        "--force-install-list",
        0,
        mod_language=1,
        game_language=fixed_game_language,
    )
    chinese_transcript = _assert_installed(game, switch_to_chinese)
    assert chinese_transcript.count("SUCCESSFULLY REMOVED") == 1
    assert chinese_transcript.count("SUCCESSFULLY INSTALLED") == 1
    assert "NOT INSTALLED DUE TO ERRORS" not in chinese_transcript
    assert "ERROR Installing" not in chinese_transcript

    after_chinese = game.snapshot()
    assert game.root_tlk.read_bytes() == baseline.root_tlk
    assert inactive_tlk.read_bytes() == inactive_baseline
    _assert_selected_runtime_catalog(
        game,
        game_language=fixed_game_language,
        catalog_directory="schinese",
        expected_tlk_strings=union_tlk_strings,
    )
    chinese_strings = _read_tlk_strings(selected_tlk)
    assert chinese_strings[1] == sentinel
    assert len(chinese_strings) - len(english_strings) == len(
        chinese_innate_strings - english_innate_strings
    )
    assert {
        name: payload
        for name, payload in after_chinese.override.items()
        if name not in {"bfbot_l10n.tra", "bfbot_strrefs.txt"}
    } == english_payload
    assert (
        after_chinese.loader_ini,
        after_chinese.root_lua51,
        after_chinese.root_provider,
    ) == helper_state
    assert _file_tree(game.root / "weidu_external/backup/buffbot/1") == helper_backup
    assert _active_buffbot_log_entries(game) == [(0, 1), (1, 0)]

    switch_back_to_english = game.run_args(
        "--force-uninstall-list",
        0,
        "--force-install-list",
        0,
        mod_language=0,
        game_language=fixed_game_language,
    )
    return_transcript = _assert_installed(game, switch_back_to_english)
    assert return_transcript.count("SUCCESSFULLY REMOVED") == 1
    assert return_transcript.count("SUCCESSFULLY INSTALLED") == 1
    assert "NOT INSTALLED DUE TO ERRORS" not in return_transcript
    assert "ERROR Installing" not in return_transcript

    after_return = game.snapshot()
    assert selected_tlk.read_bytes() == (
        after_chinese.lang_tlk
        if fixed_game_language == "en_US"
        else after_chinese.schinese_tlk
    )
    assert game.root_tlk.read_bytes() == baseline.root_tlk
    assert inactive_tlk.read_bytes() == inactive_baseline
    _assert_selected_runtime_catalog(
        game,
        game_language=fixed_game_language,
        catalog_directory="english",
        expected_tlk_strings=union_tlk_strings,
    )
    assert (
        game.override / "bfbot_l10n.tra"
    ).read_bytes() == english_catalog_bytes
    assert (
        game.override / "bfbot_strrefs.txt"
    ).read_bytes() == english_innate_refs_bytes
    assert after_return.override == after_english.override
    assert (
        after_return.loader_ini,
        after_return.root_lua51,
        after_return.root_provider,
    ) == helper_state
    assert _file_tree(game.root / "weidu_external/backup/buffbot/1") == helper_backup
    assert _active_buffbot_log_entries(game) == [(0, 1), (0, 0)]


@pytest.mark.parametrize("layout", ("v011", "v1"))
def test_language_switch_preserves_released_main_first_stack_and_keeps_ownership(
    game_factory, layout: str
) -> None:
    game = game_factory(layout)
    game.configure_loader(
        _official_loader_ini(
            (
                "LuaPatchMode=INTERNAL",
                "LuaLibrary=lua52.dll",
                "LuaVersionExternal=5.2",
            )
        )
    )
    english_sentinel = "released-stack English TLK sentinel"
    chinese_sentinel = "released-stack Chinese TLK sentinel"
    _write_tlk_strings(game.lang_tlk, ("", english_sentinel))
    _write_tlk_strings(game.schinese_tlk, ("", chinese_sentinel))
    baseline = game.snapshot()
    english_catalog, _ = parse_tra(ROOT / "buffbot/lang/english/setup.tra")
    chinese_catalog, _ = parse_tra(ROOT / "buffbot/lang/schinese/setup.tra")
    english_tlk_strings = {english_sentinel} | {
        english_catalog[catalog_id] for catalog_id in INNATE_CATALOG_IDS
    }
    chinese_tlk_strings = {chinese_sentinel} | {
        chinese_catalog[catalog_id] for catalog_id in INNATE_CATALOG_IDS
    }

    game.replace_buffbot_tp2(RELEASED_V170_TP2)
    _assert_installed(game, game.install(0))
    _assert_installed(game, game.install(1))
    game.replace_buffbot_tp2(ROOT / "buffbot/setup-buffbot.tp2")
    _assert_installed(game, game.install_many(0, 1))

    upgraded_english = game.snapshot()
    assert _active_buffbot_log_entries(game) == [(0, 0), (0, 1)]
    _assert_selected_runtime_catalog(
        game,
        game_language="en_US",
        catalog_directory="english",
        expected_tlk_strings=english_tlk_strings,
    )
    assert _read_tlk_strings(game.lang_tlk)[1] == english_sentinel
    english_catalog_bytes = (game.override / "bfbot_l10n.tra").read_bytes()
    english_innate_refs_bytes = (game.override / "bfbot_strrefs.txt").read_bytes()
    english_payload = {
        name: payload
        for name, payload in upgraded_english.override.items()
        if name not in {"bfbot_l10n.tra", "bfbot_strrefs.txt"}
    }
    helper_state = (
        upgraded_english.loader_ini,
        upgraded_english.root_lua51,
        upgraded_english.root_provider,
    )
    helper_backup = _file_tree(game.root / "weidu_external/backup/buffbot/1")
    assert helper_backup

    # Main-only forced reinstall is unsafe for the historical main->helper
    # stack: WeiDU temporarily pops the helper and main's LuaJIT gate rejects
    # before the helper is re-pushed. Selecting both installed components
    # genuinely reinstalls them while preserving the historical log order.
    switch_to_chinese = game.install_many(
        0,
        1,
        mod_language=1,
        game_language="zh_CN",
    )
    chinese_transcript = _assert_installed(game, switch_to_chinese)
    assert chinese_transcript.count("SUCCESSFULLY REMOVED") == 2
    assert chinese_transcript.count("SUCCESSFULLY INSTALLED") == 2
    assert "NOT INSTALLED DUE TO ERRORS" not in chinese_transcript
    assert "ERROR Installing" not in chinese_transcript
    assert chinese_transcript.index("SUCCESSFULLY REMOVED") < chinese_transcript.rindex(
        "SUCCESSFULLY INSTALLED"
    )

    after_chinese = game.snapshot()
    assert after_chinese.key == baseline.key
    assert after_chinese.bif == baseline.bif
    assert after_chinese.root_tlk == baseline.root_tlk
    assert after_chinese.lang_tlk == upgraded_english.lang_tlk
    assert after_chinese.schinese_tlk != baseline.schinese_tlk
    _assert_selected_runtime_catalog(
        game,
        game_language="zh_CN",
        catalog_directory="schinese",
        expected_tlk_strings=chinese_tlk_strings,
    )
    assert _read_tlk_strings(game.schinese_tlk)[1] == chinese_sentinel
    assert {
        name: payload
        for name, payload in after_chinese.override.items()
        if name not in {"bfbot_l10n.tra", "bfbot_strrefs.txt"}
    } == english_payload
    assert (
        after_chinese.loader_ini,
        after_chinese.root_lua51,
        after_chinese.root_provider,
    ) == helper_state
    chinese_helper_backup = _file_tree(
        game.root / "weidu_external/backup/buffbot/1"
    )
    assert chinese_helper_backup.keys() == helper_backup.keys()
    assert {
        name: payload
        for name, payload in chinese_helper_backup.items()
        if name != "tlkpath.1"
    } == {
        name: payload
        for name, payload in helper_backup.items()
        if name != "tlkpath.1"
    }
    assert b"zh_cn" in chinese_helper_backup["tlkpath.1"].lower()
    assert _active_buffbot_log_entries(game) == [(1, 0), (1, 1)]

    switch_back_to_english = game.install_many(
        0,
        1,
        mod_language=0,
        game_language="en_US",
    )
    return_transcript = _assert_installed(game, switch_back_to_english)
    assert return_transcript.count("SUCCESSFULLY REMOVED") == 2
    assert return_transcript.count("SUCCESSFULLY INSTALLED") == 2
    assert "NOT INSTALLED DUE TO ERRORS" not in return_transcript
    assert "ERROR Installing" not in return_transcript

    after_return = game.snapshot()
    assert after_return.lang_tlk == upgraded_english.lang_tlk
    assert after_return.schinese_tlk == after_chinese.schinese_tlk
    _assert_selected_runtime_catalog(
        game,
        game_language="en_US",
        catalog_directory="english",
        expected_tlk_strings=english_tlk_strings,
    )
    assert _read_tlk_strings(game.lang_tlk)[1] == english_sentinel
    assert (
        game.override / "bfbot_l10n.tra"
    ).read_bytes() == english_catalog_bytes
    assert (
        game.override / "bfbot_strrefs.txt"
    ).read_bytes() == english_innate_refs_bytes
    assert after_return.override == upgraded_english.override
    assert (
        after_return.loader_ini,
        after_return.root_lua51,
        after_return.root_provider,
    ) == helper_state
    assert _file_tree(game.root / "weidu_external/backup/buffbot/1") == helper_backup
    assert _active_buffbot_log_entries(game) == [(0, 0), (0, 1)]

    main_uninstall = game.uninstall(0)
    assert main_uninstall.returncode == 0, game.transcript(main_uninstall)
    assert not (game.override / "bfbot_l10n.tra").exists()
    assert not (game.override / "bfbot_l10n.txt").exists()
    after_main_uninstall = game.snapshot()
    assert (
        after_main_uninstall.loader_ini,
        after_main_uninstall.root_lua51,
        after_main_uninstall.root_provider,
    ) == helper_state
    assert _active_buffbot_log_entries(game) == [(0, 1)]
    game.assert_no_main_payload()
    helper_uninstall = game.uninstall(1)
    assert helper_uninstall.returncode == 0, game.transcript(helper_uninstall)
    after_uninstall = game.snapshot()
    assert after_uninstall.override == baseline.override
    assert after_uninstall.loader_ini == baseline.loader_ini
    assert after_uninstall.root_lua51 == baseline.root_lua51
    assert after_uninstall.root_provider == baseline.root_provider


def test_helper_and_main_share_one_exact_luajit_state_detector() -> None:
    source = (ROOT / "buffbot/setup-buffbot.tp2").read_text(encoding="utf-8")

    assert source.count("DEFINE_ACTION_FUNCTION BFBOT_DETECT_LUAJIT_STATE") == 1
    assert source.count("LAF BFBOT_DETECT_LUAJIT_STATE") == 3
    assert source.count("COUNT_REGEXP_INSTANCES ~^LuaPatchMode=~") == 1


@pytest.mark.parametrize("layout", ("v011", "v1"))
def test_main_only_rejects_inactive_luajit_without_product_mutation(
    game_factory, layout: str
) -> None:
    game = game_factory(layout)
    game.configure_loader(
        _official_loader_ini(
            (
                "LuaPatchMode=INTERNAL",
                "LuaLibrary=lua52.dll",
                "LuaVersionExternal=5.2",
            )
        )
    )
    before = game.snapshot()

    process = game.install(0)
    transcript = game.transcript(process)

    assert process.returncode != 0, transcript
    assert "SUCCESSFULLY INSTALLED" not in transcript, transcript
    assert "NOT INSTALLED" in transcript, transcript
    assert MAIN_LUAJIT_REQUIREMENT_TEXT in transcript, transcript
    assert game.snapshot() == before
    game.assert_no_main_payload()
    assert _read_tlk_strings(game.lang_tlk) == [""]


@pytest.mark.parametrize("layout", ("v011", "v1"))
def test_main_accepts_exact_external_luajit_without_buffbot_helper_ownership(
    game_factory, layout: str
) -> None:
    game = game_factory(layout, with_log=False)
    before = game.snapshot()

    process = game.install(0)

    _assert_installed(game, process)
    game.assert_main_installed(before)


@pytest.mark.parametrize("layout", ("v011", "v1"))
def test_selecting_helper_and_main_together_activates_before_main(
    game_factory, layout: str
) -> None:
    game = game_factory(layout)
    game.configure_loader(
        _official_loader_ini(
            (
                "LuaPatchMode=INTERNAL",
                "LuaLibrary=lua52.dll",
                "LuaVersionExternal=5.2",
            )
        )
    )

    process = game.install_many(0, 1)
    transcript = _assert_installed(game, process)

    assert "BuffBot: EEex LuaJIT Support" in transcript, transcript
    assert "BuffBot: In-Game Buff Automation" in transcript, transcript
    game.assert_luajit_state(game.expected_version)
    assert not MAIN_OUTPUT_FILES.isdisjoint(_file_tree(game.override))
    _assert_english_innate_catalog_in_tlk(game.lang_tlk)


@pytest.mark.parametrize("layout", ("v011", "v1"))
def test_wrong_main_first_attempt_is_safe_then_helper_allows_retry(
    game_factory, layout: str
) -> None:
    game = game_factory(layout)
    game.configure_loader(
        _official_loader_ini(
            (
                "LuaPatchMode=INTERNAL",
                "LuaLibrary=lua52.dll",
                "LuaVersionExternal=5.2",
            )
        )
    )
    before = game.snapshot()

    rejected = game.install(0)
    rejected_transcript = game.transcript(rejected)
    assert "SUCCESSFULLY INSTALLED" not in rejected_transcript, rejected_transcript
    assert MAIN_LUAJIT_REQUIREMENT_TEXT in rejected_transcript, rejected_transcript
    assert game.snapshot() == before

    helper = game.install(1)
    _assert_installed(game, helper)
    game.assert_luajit_state(game.expected_version)
    game.assert_no_main_payload()
    helper_state = game.snapshot()

    main = game.install(0)
    _assert_installed(game, main)
    game.assert_main_installed(helper_state)


@pytest.mark.parametrize("layout", ("v011", "v1"))
def test_released_main_then_helper_install_updates_under_helper_first_tp2(
    game_factory, layout: str
) -> None:
    released_source = RELEASED_V170_TP2.read_text(encoding="utf-8")
    assert released_source.index("BEGIN ~BuffBot: In-Game Buff Automation~") < (
        released_source.index("BEGIN ~BuffBot: EEex LuaJIT Support")
    )

    game = game_factory(layout)
    game.configure_loader(
        _official_loader_ini(
            (
                "LuaPatchMode=INTERNAL",
                "LuaLibrary=lua52.dll",
                "LuaVersionExternal=5.2",
            )
        )
    )
    inactive = game.snapshot()
    game.replace_buffbot_tp2(RELEASED_V170_TP2)

    released_main = game.install(0)
    _assert_installed(game, released_main)
    after_released_main = game.snapshot()
    assert after_released_main.loader_ini == inactive.loader_ini
    assert after_released_main.root_lua51 == inactive.root_lua51
    assert after_released_main.root_provider == inactive.root_provider

    released_helper = game.install(1)
    _assert_installed(game, released_helper)
    game.assert_luajit_state(game.expected_version)

    game.replace_buffbot_tp2(ROOT / "buffbot/setup-buffbot.tp2")
    update = game.install_many(0, 1)
    transcript = _assert_installed(game, update)

    assert "NOT INSTALLED" not in transcript, transcript
    assert MAIN_LUAJIT_REQUIREMENT_TEXT not in transcript, transcript
    game.assert_luajit_state(game.expected_version)
    after = game.snapshot()
    assert after.key == inactive.key
    assert after.bif == inactive.bif
    assert after.root_tlk == inactive.root_tlk
    _assert_english_innate_catalog_in_tlk(game.lang_tlk)
    assert MAIN_OUTPUT_FILES.issubset(after.override)
    assert after.override["keep.me"] == KEEP_BYTES


@pytest.mark.parametrize("layout", ("v011", "v1"))
def test_released_main_only_update_fails_safely_then_retry_recovers(
    game_factory, layout: str
) -> None:
    game = game_factory(layout)
    game.configure_loader(
        _official_loader_ini(
            (
                "LuaPatchMode=INTERNAL",
                "LuaLibrary=lua52.dll",
                "LuaVersionExternal=5.2",
            )
        )
    )
    game.replace_buffbot_tp2(RELEASED_V170_TP2)
    _assert_installed(game, game.install(0))
    _assert_installed(game, game.install(1))
    game.assert_luajit_state(game.expected_version)
    released = game.snapshot()

    game.replace_buffbot_tp2(ROOT / "buffbot/setup-buffbot.tp2")
    update = game.install(0)
    transcript = game.transcript(update)

    assert update.returncode != 0, transcript
    assert MAIN_LUAJIT_REQUIREMENT_TEXT in transcript, transcript
    assert "NOT INSTALLED" in transcript, transcript
    game.assert_luajit_state(game.expected_version)
    game.assert_no_main_payload()

    failed = game.snapshot()
    assert failed.key == released.key
    assert failed.bif == released.bif
    assert failed.root_tlk == released.root_tlk
    assert failed.lang_tlk == released.lang_tlk
    assert failed.eeex == released.eeex
    assert failed.eeex_scripts == released.eeex_scripts
    assert failed.loader_ini == released.loader_ini
    assert failed.root_lua51 == released.root_lua51
    assert failed.root_provider == released.root_provider
    assert failed.override == {
        name: payload
        for name, payload in released.override.items()
        if name not in MAIN_OUTPUT_FILES
    }

    active_log = [
        line.replace("\\", "/").casefold()
        for line in (game.root / "WeiDU.log").read_text(encoding="utf-8").splitlines()
        if line.startswith("~")
    ]
    assert any("buffbot/setup-buffbot.tp2~ #0 #1" in line for line in active_log)
    assert not any("buffbot/setup-buffbot.tp2~ #0 #0" in line for line in active_log)

    retry = game.install(0)
    _assert_installed(game, retry)
    game.assert_luajit_state(game.expected_version)
    after_retry = game.snapshot()
    assert after_retry.loader_ini == failed.loader_ini
    assert after_retry.root_lua51 == failed.root_lua51
    assert after_retry.root_provider == failed.root_provider
    assert MAIN_OUTPUT_FILES.issubset(after_retry.override)
    assert after_retry.override["bfbotper.lua"] == (
        ROOT / "buffbot/BfBotPer.lua"
    ).read_bytes()


@pytest.mark.parametrize("layout", ("v011", "v1"))
def test_explicit_helper_removal_does_not_seed_main_lifecycle_exception(
    game_factory, layout: str
) -> None:
    game = game_factory(layout)
    game.configure_loader(
        _official_loader_ini(
            (
                "LuaPatchMode=INTERNAL",
                "LuaLibrary=lua52.dll",
                "LuaVersionExternal=5.2",
            )
        )
    )
    inactive = game.snapshot()

    helper = game.install(1)
    _assert_installed(game, helper)
    game.assert_luajit_state(game.expected_version)

    removal_and_main = game.uninstall_then_install(1, 0)
    transcript = game.transcript(removal_and_main)
    assert removal_and_main.returncode != 0, transcript
    assert "SUCCESSFULLY REMOVED" in transcript, transcript
    assert MAIN_LUAJIT_REQUIREMENT_TEXT in transcript, transcript
    assert "NOT INSTALLED" in transcript, transcript
    assert game.snapshot() == inactive
    game.assert_no_main_payload()

    fresh_main = game.install(0)
    fresh_transcript = game.transcript(fresh_main)
    assert fresh_main.returncode != 0, fresh_transcript
    assert MAIN_LUAJIT_REQUIREMENT_TEXT in fresh_transcript, fresh_transcript
    assert game.snapshot() == inactive


@pytest.mark.parametrize("layout", ("v011", "v1"))
def test_legacy_helper_ownership_survives_main_uninstall_then_restores(
    game_factory, layout: str
) -> None:
    game = game_factory(layout)
    game.configure_loader(
        _official_loader_ini(
            (
                "LuaPatchMode=INTERNAL",
                "LuaLibrary=lua52.dll",
                "LuaVersionExternal=5.2",
            )
        ),
        root_lua51=b"legacy root lua51.dll\0",
        root_provider=b"legacy root LuaProvider.dll\0",
    )
    before = game.snapshot()

    helper = game.install(1)
    _assert_installed(game, helper)
    helper_state = game.snapshot()
    main = game.install(0)
    _assert_installed(game, main)

    main_uninstall = game.uninstall(0)
    main_uninstall_transcript = game.transcript(main_uninstall)
    assert main_uninstall.returncode == 0, main_uninstall_transcript
    assert "NOT UNINSTALLED" not in main_uninstall_transcript, main_uninstall_transcript
    game.assert_no_main_payload()
    assert not (game.override / "bfbot_l10n.tra").exists()
    assert not (game.override / "bfbot_l10n.txt").exists()
    after_main_uninstall = game.snapshot()
    assert after_main_uninstall.loader_ini == helper_state.loader_ini
    assert after_main_uninstall.root_lua51 == helper_state.root_lua51
    assert after_main_uninstall.root_provider == helper_state.root_provider

    helper_uninstall = game.uninstall(1)
    helper_uninstall_transcript = game.transcript(helper_uninstall)
    assert helper_uninstall.returncode == 0, helper_uninstall_transcript
    assert "NOT UNINSTALLED" not in helper_uninstall_transcript, helper_uninstall_transcript
    after = game.snapshot()
    assert after.loader_ini == before.loader_ini
    assert after.root_lua51 == before.root_lua51
    assert after.root_provider == before.root_provider
    assert after.override == before.override
    assert after.eeex == before.eeex
    assert after.eeex_scripts == before.eeex_scripts
    _assert_english_innate_catalog_in_tlk(game.lang_tlk)


@pytest.mark.parametrize("newline", ("\n", "\r\n"), ids=("lf", "crlf"))
@pytest.mark.parametrize("layout", ("v011", "v1"))
def test_luajit_exact_active_state_is_byte_identical(
    game_factory, layout: str, newline: str
) -> None:
    game = game_factory(layout)
    game.set_exact_active_loader(newline)
    before = game.snapshot()
    process = game.install(1)
    _assert_installed(game, process)
    assert "LuaJIT is already active" in game.transcript(process)
    assert game.snapshot() == before


@pytest.mark.parametrize("newline", ("\n", "\r\n"), ids=("lf", "crlf"))
@pytest.mark.parametrize("layout", ("v011", "v1"))
def test_luajit_custom_section_before_auto_does_not_count_as_general(
    game_factory, layout: str, newline: str
) -> None:
    game = game_factory(layout)
    version = game.expected_version
    game.configure_loader(
        _loader_with_custom_section_before_auto(version, newline),
        root_lua51=SOURCE_LUA51,
        root_provider=SOURCE_PROVIDER,
    )

    process = game.install(1)
    transcript = _assert_installed(game, process)
    assert "LuaJIT is already active" not in transcript, transcript
    normalized = (game.root / "InfinityLoader.ini").read_text(encoding="ascii")
    _assert_only_general_luajit_assignments(normalized, version)
    assert "[Custom]" in normalized
    assert "SyntheticCustomValue=preserve-custom" in normalized

    repeat = game_factory(layout)
    repeat.configure_loader(
        normalized,
        root_lua51=SOURCE_LUA51,
        root_provider=SOURCE_PROVIDER,
    )
    repeat_before = repeat.snapshot()
    repeat_process = repeat.install(1)
    _assert_installed(repeat, repeat_process)
    assert "LuaJIT is already active" in repeat.transcript(repeat_process)
    assert repeat.snapshot() == repeat_before


@pytest.mark.parametrize("layout", ("v011", "v1"))
@pytest.mark.parametrize(
    ("case", "general_assignments", "hardcoded_assignments"),
    (
        (
            "missing_from_general",
            (),
            (
                "LuaPatchMode=REPLACE_INTERNAL_WITH_EXTERNAL",
                "LuaLibrary=lua51.dll",
                "LuaVersionExternal={version}",
            ),
        ),
        (
            "duplicates",
            (
                "LuaPatchMode=INTERNAL",
                "LuaPatchMode=REPLACE_INTERNAL_WITH_EXTERNAL",
                "LuaLibrary=lua52.dll",
                "LuaLibrary=lua51.dll",
                "LuaVersionExternal=5.2",
                "LuaVersionExternal={version}",
            ),
            ("LuaLibrary=lua51.dll",),
        ),
    ),
    ids=("missing-keys", "duplicate-keys"),
)
def test_luajit_normalizes_assignments_only_in_general_section(
    game_factory,
    layout: str,
    case: str,
    general_assignments: tuple[str, ...],
    hardcoded_assignments: tuple[str, ...],
) -> None:
    game = game_factory(layout)
    version = game.expected_version
    ini = _official_loader_ini(
        tuple(line.format(version=version) for line in general_assignments),
        tuple(line.format(version=version) for line in hardcoded_assignments),
    )
    game.configure_loader(
        ini,
        root_lua51=SOURCE_LUA51,
        root_provider=SOURCE_PROVIDER,
    )

    process = game.install(1)
    transcript = _assert_installed(game, process)
    assert "LuaJIT is already active" not in transcript, (case, transcript)
    normalized = (game.root / "InfinityLoader.ini").read_text(encoding="ascii")
    _assert_only_general_luajit_assignments(normalized, version)

    # A fresh install over the normalized product must take the byte-identical
    # already-active path, proving the output is accepted by the detector.
    repeat = game_factory(layout)
    repeat.configure_loader(
        normalized,
        root_lua51=SOURCE_LUA51,
        root_provider=SOURCE_PROVIDER,
    )
    repeat_before = repeat.snapshot()
    repeat_process = repeat.install(1)
    _assert_installed(repeat, repeat_process)
    assert "LuaJIT is already active" in repeat.transcript(repeat_process)
    assert repeat.snapshot() == repeat_before


@pytest.mark.parametrize("layout", ("v011", "v1"))
@pytest.mark.parametrize("root_state", ("distinct", "absent"))
def test_luajit_component_uninstall_restores_exact_preinstall_files(
    game_factory, layout: str, root_state: str
) -> None:
    game = game_factory(layout)
    old_lua51 = b"pre-existing distinct root lua51.dll\0"
    old_provider = b"pre-existing distinct root LuaProvider.dll\0"
    game.configure_loader(
        _official_loader_ini(
            (
                "LuaPatchMode=INTERNAL",
                "LuaLibrary=an-old-library.dll",
                "LuaVersionExternal=an-old-version",
            )
        ),
        root_lua51=old_lua51 if root_state == "distinct" else None,
        root_provider=old_provider if root_state == "distinct" else None,
    )
    before = game.snapshot()

    install = game.install(1)
    _assert_installed(game, install)
    assert game.snapshot() != before

    uninstall = game.uninstall(1)
    transcript = game.transcript(uninstall)
    assert uninstall.returncode == 0, transcript
    assert "NOT UNINSTALLED" not in transcript, transcript
    assert game.snapshot() == before


@pytest.mark.parametrize("layout", ("v011", "v1"))
@pytest.mark.parametrize(
    "ini",
    (
        "[Auto-Generated]\nLuaPatchMode=INTERNAL\n",
        "[General]\nDebug=0\n[General]\nPause=0\n",
    ),
    ids=("missing-general", "duplicate-general"),
)
def test_luajit_malformed_general_fails_before_mutation(
    game_factory, layout: str, ini: str
) -> None:
    game = game_factory(layout)
    game.configure_loader(
        ini,
        root_lua51=b"pre-existing root lua51.dll\0",
        root_provider=b"pre-existing root LuaProvider.dll\0",
    )
    before = game.snapshot()

    process = game.install(1)
    transcript = game.transcript(process)
    assert process.returncode != 0, transcript
    assert "SUCCESSFULLY INSTALLED" not in transcript, transcript
    assert "well-formed first [General] section" in transcript, transcript
    assert game.snapshot() == before


@pytest.mark.parametrize("layout", ("v011", "v1"))
def test_commented_library_decoy_does_not_satisfy_active_state(
    game_factory, layout: str
) -> None:
    game = game_factory(layout)
    game.configure_loader(
        _official_loader_ini(
            (
                "; LuaLibrary=lua51.dll",
                "LuaPatchMode=REPLACE_INTERNAL_WITH_EXTERNAL",
                f"LuaVersionExternal={game.expected_version}",
            )
        ),
        root_lua51=SOURCE_LUA51,
        root_provider=SOURCE_PROVIDER,
    )
    before = game.snapshot()
    assert before.loader_ini is not None
    before_ini = before.loader_ini.decode("ascii")
    assert "; LuaLibrary=lua51.dll" in before_ini
    assert not re.search(r"(?m)^LuaLibrary=", before_ini)

    process = game.install(1)
    transcript = _assert_installed(game, process)
    assert "LuaJIT is already active" not in transcript
    assert "Installing EEex LuaJIT component" in transcript
    game.assert_luajit_state(game.expected_version)

    after = game.snapshot()
    assert after.loader_ini != before.loader_ini
    assert after.key == before.key
    assert after.bif == before.bif
    assert after.root_tlk == before.root_tlk
    assert after.lang_tlk == before.lang_tlk
    assert after.override == before.override
    assert after.eeex == before.eeex
    assert after.eeex_scripts == before.eeex_scripts
    assert after.root_lua51 == before.root_lua51
    assert after.root_provider == before.root_provider


@pytest.mark.parametrize(
    ("layout", "tp2_contents"),
    (
        ("v011", None),
        ("v1", None),
        ("v1", "// stale metadata says LuaVersionExternal=5.1\n"),
    ),
)
def test_luajit_inactive_state_uses_capability_family_not_tp2_text(
    game_factory, layout: str, tp2_contents: str | None
) -> None:
    game = game_factory(layout)
    game.set_tp2(tp2_contents)
    game.configure_loader(
        _official_loader_ini(
            (
                "LuaPatchMode=INTERNAL",
                "LuaLibrary=lua52.dll",
                "LuaVersionExternal=5.2",
            )
        )
    )
    before = game.snapshot()
    process = game.install(1)
    _assert_installed(game, process)
    game.assert_luajit_state(game.expected_version)
    after = game.snapshot()
    assert after.key == before.key
    assert after.bif == before.bif
    assert after.root_tlk == before.root_tlk
    assert after.lang_tlk == before.lang_tlk
    assert after.override == before.override
    assert after.eeex == before.eeex
    assert after.eeex_scripts == before.eeex_scripts


@pytest.mark.parametrize("layout", ("v011", "v1"))
def test_luajit_patch_mode_without_complete_state_is_repaired(
    game_factory, layout: str
) -> None:
    game = game_factory(layout)
    game.configure_loader(
        _official_loader_ini(
            (
                "; LuaLibrary=lua51.dll must not satisfy the active check",
                "LuaPatchMode=REPLACE_INTERNAL_WITH_EXTERNAL",
            )
        ),
        root_lua51=SOURCE_LUA51,
        root_provider=None,
    )
    before = game.snapshot()
    process = game.install(1)
    _assert_installed(game, process)
    game.assert_luajit_state(game.expected_version)
    after = game.snapshot()
    assert after.lang_tlk == before.lang_tlk
    assert after.root_tlk == before.root_tlk
    assert after.override == before.override


@pytest.mark.parametrize("layout", ("v011", "v1"))
@pytest.mark.parametrize("missing", ("lua51", "provider", "ini"))
def test_luajit_missing_prerequisite_fails_before_mutation_and_rolls_back(
    game_factory, layout: str, missing: str
) -> None:
    game = game_factory(layout)
    game.configure_loader(
        None
        if missing == "ini"
        else _official_loader_ini(
            (
                "LuaPatchMode=INTERNAL",
                "LuaLibrary=lua52.dll",
                "LuaVersionExternal=5.2",
            )
        )
    )
    if missing == "lua51":
        game.source_lua51.unlink()
    elif missing == "provider":
        game.source_provider.unlink()
    before = game.snapshot()
    process = game.install(1)
    transcript = game.transcript(process)
    assert "SUCCESSFULLY INSTALLED" not in transcript, transcript
    assert "NOT INSTALLED" in transcript, transcript
    expected = "InfinityLoader.ini" if missing == "ini" else "source DLLs"
    assert expected in transcript, transcript
    assert game.snapshot() == before
    assert _read_tlk_strings(game.lang_tlk) == [""]


def test_v1_component_one_log_without_component_eight_still_activates(
    game_factory,
) -> None:
    game = game_factory("v1")
    assert "#1" in (game.root / "WeiDU.log").read_text(encoding="ascii")
    assert "#8" not in (game.root / "WeiDU.log").read_text(encoding="ascii")
    game.configure_loader(
        _official_loader_ini(
            (
                "LuaPatchMode=INTERNAL",
                "LuaLibrary=lua52.dll",
                "LuaVersionExternal=5.2",
            )
        )
    )
    process = game.install(1)
    _assert_installed(game, process)
    game.assert_luajit_state("5.1-LuaJIT")


@pytest.mark.parametrize("layout", ("v011", "v1"))
def test_main_component_uninstall_leaves_stable_tlk_residue_and_reuses_it(
    game_factory, layout: str
) -> None:
    game = game_factory(layout)
    before = game.snapshot()
    first_install = game.install(0)
    _assert_installed(game, first_install)
    game.assert_main_installed(before)
    first_tlk = game.lang_tlk.read_bytes()

    uninstall = game.uninstall(0)
    transcript = game.transcript(uninstall)
    assert uninstall.returncode == 0, transcript
    assert "NOT UNINSTALLED" not in transcript, transcript
    assert not (game.override / "bfbot_l10n.tra").exists()
    assert not (game.override / "bfbot_l10n.txt").exists()
    assert _file_tree(game.override) == before.override
    game.assert_no_main_payload()
    assert game.lang_tlk.read_bytes() == first_tlk
    _assert_english_innate_catalog_in_tlk(game.lang_tlk)
    assert game.root_tlk.read_bytes() == before.root_tlk

    second_install = game.install(0)
    _assert_installed(game, second_install)
    assert game.lang_tlk.read_bytes() == first_tlk
    _assert_english_innate_catalog_in_tlk(game.lang_tlk)

def test_installer_accepts_iwdee_for_helper_and_main() -> None:
    source = (ROOT / "buffbot/setup-buffbot.tp2").read_text(encoding="utf-8")
    predicate = "REQUIRE_PREDICATE (GAME_IS ~bgee bg2ee eet iwdee~)"

    assert source.count(predicate) == 2
